### PR TITLE
make Doom sound quirk fixes available on all complevels

### LINKED ISSUE #302: Sounds are cutting off other sounds when using -complevel 2, 3, and 4
I first noticed this with complevel 2. The most prominent example of it occurring is whenever you use the pistol against a zombieman and the sound of the pistol shot that kills the zombieman is sometimes cut off by their death scream. It occurs most often when you use the pistol against them at close range.

I tested to see if this was just hard-coded behavior with sounds using complevel 2 by seeing if the same thing happens in Chocolate Doom but it didn't occur there. I then checked to see if it also occurred on other complevels and it did for 3 and 4. However the bug didn't seem to happen on complevels 9 and 11.

_(Just to clarify, this is not related to how sounds are abruptly stopped when the actor playing them are deleted.)_

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #302

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Hm, I could just as well leave the checks in `p_inter.c` and `p_pspr.c` (any others?) intact.

File: prboom2/src/p_genlin.c [hunk 1]
```diff
@@ -1138,28 +1138,28 @@ int EV_DoGenDoor
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         if (door->topheight != sec->ceilingheight)
-          S_StartSound((mobj_t *)&door->sector->soundorg,Sped>=SpeedFast || comp[comp_sound] ? sfx_bdopn : sfx_doropn);
+          S_StartSound((mobj_t *)&door->sector->soundorg,Sped>=SpeedFast || default_comp[comp_sound] ? sfx_bdopn : sfx_doropn);
```
Comment (fabiangreffrath) [inline prboom2/src/p_genlin.c:1141]: EE unconditionally plays `sfx_bdopn` here.

File: prboom2/src/p_genlin.c [hunk 2]
```diff
@@ -1138,28 +1138,28 @@ int EV_DoGenDoor
...
         door->type = Sped>=SpeedFast? genBlazeRaise : genRaise;
         break;
       case ODoor:
         door->direction = 1;
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         if (door->topheight != sec->ceilingheight)
-          S_StartSound((mobj_t *)&door->sector->soundorg,Sped>=SpeedFast || comp[comp_sound] ? sfx_bdopn : sfx_doropn);
+          S_StartSound((mobj_t *)&door->sector->soundorg,Sped>=SpeedFast || default_comp[comp_sound] ? sfx_bdopn : sfx_doropn);
```
Comment (fabiangreffrath) [inline prboom2/src/p_genlin.c:1149]: EE unconditionally plays `sfx_bdopn` here.

File: prboom2/src/p_genlin.c [hunk 3]
```diff
@@ -1138,28 +1138,28 @@ int EV_DoGenDoor
...
         door->type = Sped>=SpeedFast? genBlazeOpen : genOpen;
         break;
       case CdODoor:
         door->topheight = sec->ceilingheight;
         door->direction = -1;
-        S_StartSound((mobj_t *)&door->sector->soundorg,Sped>=SpeedFast && !comp[comp_sound] ? sfx_bdcls : sfx_dorcls);
+        S_StartSound((mobj_t *)&door->sector->soundorg,Sped>=SpeedFast && !default_comp[comp_sound] ? sfx_bdcls : sfx_dorcls);
```
Comment (fabiangreffrath) [inline prboom2/src/p_genlin.c:1155]: EE unconditionally plays `sfx_dorcls` here.

File: prboom2/src/p_genlin.c [hunk 4]
```diff
@@ -1138,28 +1138,28 @@ int EV_DoGenDoor
...
         door->type = Sped>=SpeedFast? genBlazeCdO : genCdO;
         break;
       case CDoor:
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         door->direction = -1;
-        S_StartSound((mobj_t *)&door->sector->soundorg,Sped>=SpeedFast && !comp[comp_sound] ? sfx_bdcls : sfx_dorcls);
+        S_StartSound((mobj_t *)&door->sector->soundorg,Sped>=SpeedFast && !default_comp[comp_sound] ? sfx_bdcls : sfx_dorcls);
```
Comment (fabiangreffrath) [inline prboom2/src/p_genlin.c:1162]: EE unconditionally plays `sfx_dorcls` here.

File: prboom2/src/p_inter.c [hunk 5]
```diff
@@ -191,7 +191,7 @@ static dboolean P_GiveWeapon(player_t *player, weapontype_t weapon, dboolean dro
       /* cph 20028/10 - for old-school DM addicts, allow old behavior
        * where only consoleplayer's pickup sounds are heard */
       // displayplayer, not consoleplayer, for viewing multiplayer demos
-      if (!comp[comp_sound] || player == &players[displayplayer])
+      if (!default_comp[comp_sound] || player == &players[displayplayer])
```
Comment (fabiangreffrath) [inline prboom2/src/p_inter.c:194]: EE plays the sound unconditionally.

File: prboom2/src/p_inter.c [hunk 6]
```diff
@@ -632,7 +632,7 @@ void P_TouchSpecialThing(mobj_t *special, mobj_t *toucher)
   /* cph 20028/10 - for old-school DM addicts, allow old behavior
    * where only consoleplayer's pickup sounds are heard */
   // displayplayer, not consoleplayer, for viewing multiplayer demos
-  if (!comp[comp_sound] || player == &players[displayplayer])
+  if (!default_comp[comp_sound] || player == &players[displayplayer])
     S_StartSound (player->mo, sound | PICKUP_SOUND);   // killough 4/25/98
```
Comment (fabiangreffrath) [inline prboom2/src/p_inter.c:636]: EE plays the sound unconditionally.

File: prboom2/src/p_map.c [hunk 7]
```diff
@@ -1850,7 +1850,7 @@ void P_UseLines (player_t*  player)
   // This added test makes the "oof" sound work on 2s lines -- killough:
 
   if (P_PathTraverse ( x1, y1, x2, y2, PT_ADDLINES, PTR_UseTraverse ))
-    if (!comp[comp_sound] && !P_PathTraverse ( x1, y1, x2, y2, PT_ADDLINES, PTR_NoWayTraverse ))
+    if (!default_comp[comp_sound] && !P_PathTraverse ( x1, y1, x2, y2, PT_ADDLINES, PTR_NoWayTraverse ))
```
Comment (fabiangreffrath) [inline prboom2/src/p_map.c:1853]: EE plays the sound without further conditions.

File: prboom2/src/p_mobj.c [hunk 8]
```diff
@@ -608,7 +608,7 @@ static void P_ZMovement (mobj_t* mo)
 
         mo->player->deltaviewheight = mo->momz>>3;
         //e6y: compatibility optioned
-        if (comp[comp_sound] || (mo->health>0)) /* cph - prevent "oof" when dead */
+        if (default_comp[comp_sound] || (mo->health>0)) /* cph - prevent "oof" when dead */
     S_StartSound (mo, sfx_oof);
```
Comment (fabiangreffrath) [inline prboom2/src/p_mobj.c:612]: EE plays the sound unconditionally.

File: prboom2/src/p_pspr.c [hunk 9]
```diff
@@ -850,7 +850,7 @@ void A_FireCGun(player_t *player, pspdef_t *psp)
 {
   CHECK_WEAPON_CODEPOINTER("A_FireCGun", player);
 
-  if (player->ammo[weaponinfo[player->readyweapon].ammo] || comp[comp_sound])
+  if (player->ammo[weaponinfo[player->readyweapon].ammo] || default_comp[comp_sound])
```
Comment (fabiangreffrath) [inline prboom2/src/p_pspr.c:853]: EE plays the sound unconditionally.

File: prboom2/src/p_setup.c [hunk 10]
```diff
@@ -2250,7 +2250,7 @@ static int P_GroupLines (void)
     sector->bbox[3] = sector->blockbox[3] >> FRACTOMAPBITS;
 
     // set the degenmobj_t to the middle of the bounding box
-    if (comp[comp_sound])
+    if (default_comp[comp_sound])
```
Comment (fabiangreffrath) [inline prboom2/src/p_setup.c:2253]: EE follows the first code path, i.e. without the fix for large levels.

File: prboom2/src/p_spec.c [hunk 11]
```diff
@@ -2540,7 +2540,7 @@ void P_UpdateSpecials (void)
           /* don't take the address of the switch's sound origin,
            * unless in a compatibility mode. */
           mobj_t *so = (mobj_t *)buttonlist[i].soundorg;
-          if (comp[comp_sound] || compatibility_level < prboom_6_compatibility)
+          if (default_comp[comp_sound] || compatibility_level < prboom_6_compatibility)
```
Comment (fabiangreffrath) [inline prboom2/src/p_spec.c:2543]: EE plays the sound unconditionally from the unfixed "address of" soundorg.

File: prboom2/src/p_switch.c [hunk 12]
```diff
@@ -180,7 +180,7 @@ void P_ChangeSwitchTexture
   /* use the sound origin of the linedef (its midpoint)
    * unless in a compatibility mode */
   soundorg = (mobj_t *)&line->soundorg;
-  if (comp[comp_sound] || compatibility_level < prboom_6_compatibility) {
+  if (default_comp[comp_sound] || compatibility_level < prboom_6_compatibility) {
     /* usually NULL, unless there is another button already pressed in,
      * in which case it's the sound origin of that button press... */
     soundorg = buttonlist->soundorg;
```
Comment (fabiangreffrath) [inline prboom2/src/p_switch.c:186]: EE unconditionally always plays the sounds from `buttonlist->soundorg`.

File: prboom2/src/s_sound.c [hunk 13]
```diff
@@ -324,7 +324,7 @@ void S_StartSoundAtVolume(void *origin_p, int sfx_id, int volume)
   // kill old sound
   for (cnum=0 ; cnum<numChannels ; cnum++)
     if (channels[cnum].sfxinfo && channels[cnum].origin == origin &&
-        (comp[comp_sound] || channels[cnum].is_pickup == is_pickup))
+        (default_comp[comp_sound] || channels[cnum].is_pickup == is_pickup))
```
Comment (fabiangreffrath) [inline prboom2/src/s_sound.c:327]: EE replaces the check for `is_pickup` with one for `singularity` but doesn't apply any other checks.

**Comment by fabiangreffrath** [comment]
> I think in the eternity source there are checks for these fixes based on the context, instead of having the comp option. Maybe the differences there could be adopted. I don't really know enough about it to have specific places in the code in mind though 😅

I have gone through all the relevant places in the EE source code to check what they do there. Indeed, they don't have a compat flag but always choose one way or the other. Thus, I think it would be fine for Pr+ to have the user setting in the menu and switch between one solution (i.e. the "fixed" one) and the other (i.e. the "quirks" one). BTW, Crispy does also have only one global "Sound fixes" switch that does mostly the same.
