### PR TITLE
Fix hanging notes on exit when using Portmidi (fixes #232)

### LINKED ISSUE #232: PortMIDI backend won't stop notes after exiting game
The PortMIDI music backend is simple and good enough - it sends MIDI events to an output MIDI sink in the system.

There is one issue with that - it doesn't stop ("panic") MIDI channels after the program exits, which often leads to notes that don't end.

In my particular setup (w/ Manjaro Linux), I use ALSA for MIDI routing, and run a FluidSynth daemon with systemd and an user service. Then, using QjackCtl's graph, I connect the MIDI Through input to the FluidSynth output port. MIDI Through is in its essence a loopback, and thus what this does is it plugs all events that go to MIDI Through back and through FluidSynth. Yes, I have defined a QjackCtl patchbay configuration so it does this connection automatically for me now. Just some context, don't think any of these are the culprit.

An easy solution would be to send a MIDI panic on all channels when PrBoom+ exits whilst using the PortMIDI backend. Make sure to do this on all shutdowns, including I_Error ones! If anything, just check if a song was playing at this current state (if not, no need to send panics).

### PR DESCRIPTION
**Pull request by Gustavo6046**
When using the PortMidi player, e.g. in an ALSA MIDI setup, closing the program often [leaves some hanging notes](https://github.com/coelckers/prboom-plus/issues/232), since they aren't stopped by the game when it exits.

This hopefully fixes it by sending a MIDI ~~Stop All Sound~~ All Notes Off message to all channels in the shutdown callback, right before actually shutting PortMidi itself down, and by allowing the delay between that and the Portmidi shutdown to happen on non-Win32 platforms too.

Also, for the sake of linkage. Fixes #232 .

### CODE REVIEW

File: prboom2/src/MUSIC/portmidiplayer.c [hunk 1]
```diff
@@ -178,6 +178,32 @@ static int pm_init (int samplerate)
...
 }
 
+#ifndef MIDI_EVENT_CHANNEL_MODE
+
+// channel mode events in MIDI, low nibble is channel value as usual
+#define MIDI_EVENT_CHANNEL_MODE 0xB0
+
+#endif
+
+static void pm_killnotes (unsigned long when = 0)
```
Comment (alexey-lysiuk) [inline prboom2/src/MUSIC/portmidiplayer.c:188]: C language doesn't support default values, it's a C++ thing.

Comment (Gustavo6046) [reply prboom2/src/MUSIC/portmidiplayer.c]: Yeah, I noticed that with the CI failure. I was just pushing commits to fix that :p

**Comment by Gustavo6046** [comment]
Build seems to be working now. I'll do on my end too. If all goes well I should be able to test in a moment.

**Comment by Gustavo6046** [comment]
Unfortunately it doesn't stop hanging notes from occurring. I am not sure why yet. I will investigate.

**Comment by Gustavo6046** [comment]
`pm_killnotes` _is_ called, according to gdb. So the issue is probably with the event sent, or how it is sent, or maybe it's the fact that `Pm_Close` is called right after `Pm_Write` (`writeevent`)? Maybe it doesn't _actually_ send the event because of that? I'm not sure. Is there a `Pm_Flush` type function I could call to work around this, at least for now?

File: prboom2/src/MUSIC/portmidiplayer.c [hunk 2]
```diff
@@ -207,6 +232,9 @@ static void pm_shutdown (void)
     Pt_Sleep (DRIVER_LATENCY * 2);
     #endif
 
+	// stop all sound, in case of hanging notes
+    pm_killnotes(0);
```
Comment (fabiangreffrath) [inline prboom2/src/MUSIC/portmidiplayer.c:236]: Couldn't you just call `pm_stop()` here?

Comment (Gustavo6046) [reply prboom2/src/MUSIC/portmidiplayer.c:236]: Good point, I'll do that.

Comment (Gustavo6046) [reply prboom2/src/MUSIC/portmidiplayer.c]: It also seems insufficient - hanging notes still occur. I'll investigate further.

**Comment by Gustavo6046** [comment]
Thanks Fabian, pm_stop does seem to be precisely what pm_killnotes aspired to be :p

Unfortunately, it still doesn't resolve the issue.

Perhaps it isn't a prboom-plus issue - `aplaymidi` also doesn't stop notes if it is interrupted prematurely with Ctrl+C (aka `sigint`), although that might be by design since it's meant to play MIDI events directly, and probably not supposed to be a MIDI player of sorts.

On the other hand, Drumstick doesn't seem to be affected by this issue. It's a simple MIDI player, so I suppose it is expected to stop ongoing notes if it closes before the end of a song.

Perhaps a better "fix" would be to just add an ALSA MIDI backend for Linux builds? Hmm.

**Comment by Gustavo6046** [comment]
You know what, scratch Portmidi. Feel free to close this PR if you feel like it is going nowhere. My efforts might be better invested into implementing an ALSA MIDI backend. If all goes well I might even add a JACK one in the near future, or even a TCP one. I dunno.

**Comment by fabiangreffrath** [comment]
Hm, I am surprised the latest commit doesn't fix the issue for you. Would you mind having a look at the shutdown sequence in Drumstick, i.e. which portmidi functions are called there?

**Comment by Gustavo6046** [comment]
I'm not sure if Drumstick uses Portmidi. If it doesn't, there's our answer.

I'm currently working on an ALSA interface, which is basically a weird port of portmidiplayer.c to the [ALSA Sequencer API](https://www.alsa-project.org/alsa-doc/alsa-lib/seq.html). If all goes well, we might have this in the preference list above Portmidi! (CMakeLists.txt will look for ALSA, so don't worry about portability, as it'll be skipped for non-Linux users anyway.)

**Comment by fabiangreffrath** [comment]
I am still not giving up on this one. It might as well be a timing problem: The "All Notes Off" command is sent to a pm "device" that is shut down in the very same moment.

Could you try setting `when` to `0` in `pm_stop()` (which means *now* if I am not mistaken), please?

**Comment by Gustavo6046** [comment]
Setting `when` to `0` inside `pm_stop()` sadly does not fix the issue.

**Comment by fabiangreffrath** [comment]
What if you remove the condition around that `Pt_Sleep()` call a few lines farther?

**Comment by Gustavo6046** [comment]
> What if you remove the condition around that `Pt_Sleep()` call a few lines farther?

Well, that seems to fix it!

That does make the semantics of the comment preceding it a tad silly. :P

**Comment by Gustavo6046** [comment]
Also, for the sake of linkage. Fixes #232 .

File: prboom2/src/MUSIC/portmidiplayer.c [hunk 3]
```diff
@@ -385,7 +388,7 @@ static void writesysex (unsigned long when, int etype, unsigned char *data, int
 static void pm_stop (void)
 {
   int i;
-  unsigned long when = Pt_Time ();
+  unsigned long when = 0;
```
Comment (fabiangreffrath) [inline prboom2/src/MUSIC/portmidiplayer.c:391]: I guess it's safe to revert this change back to the original code.

**Review by fabiangreffrath — CHANGES_REQUESTED** [review]

File: prboom2/src/MUSIC/portmidiplayer.c (hunk 3 above)
Comment (Gustavo6046) [reply prboom2/src/MUSIC/portmidiplayer.c:391]: I think so too.

**Comment by fabiangreffrath** [comment]
Thank you!

**Comment by Gustavo6046** [comment]
Why of course :)
